#!/bin/bash

cd /usr/src/linux-2.4.18-14custom
make bzImage
read -r -p "Hit any key to continue..." response

make modules
make modules_install
cd arch/i386/boot
cp bzImage/boot/vmlinuz-2.4.18-14custom -f
cd /boot
mkinitrd 2.4.18-14custom.img 2.4.18-14custom

read -r -p "Hit any key to reboot..." response

reboot
