#!/bin/bash

cp -u linux-2.4.18-14custom/arch/i386/kernel/entry.S		/usr/src/linux-2.4.18-14custom/arch/i386/kernel/
cp -u linux-2.4.18-14custom/include/asm-i386/unistd.h		/usr/src/linux-2.4.18-14custom/include/asm-i386/
cp -u linux-2.4.18-14custom/include/linux/sched.h			/usr/src/linux-2.4.18-14custom/include/linux/
cp -u linux-2.4.18-14custom/kernel/fork.c					/usr/src/linux-2.4.18-14custom/kernel/
cp -u linux-2.4.18-14custom/kernel/sched.c					/usr/src/linux-2.4.18-14custom/kernel/


cp -u hw2_syscalls.h			/usr/src/linux-2.4.18-14custom/
cp -u main.c					/root/

cp -u ../compileKernel			/root/




cp -u linux-2.4.18-14custom/arch/i386/kernel/traps.c		/usr/src/linux-2.4.18-14custom/arch/i386/kernel/
cp -u linux-2.4.18-14custom/kernel/ctx_log.h					/usr/src/linux-2.4.18-14custom/kernel/
cp -u linux-2.4.18-14custom/kernel/exit.c					/usr/src/linux-2.4.18-14custom/kernel/
cp -u linux-2.4.18-14custom/kernel/kassert.h					/usr/src/linux-2.4.18-14custom/kernel/

cp -a -u test_logger_src/user_mode/.			/root/
cp -u hw2_syscalls.h							/root/
cp -u runTest									/root/


cp -a -u test_simple/.							/root/

cp -u simpleTest								/root/


#echo Done copying!
