#!/bin/bash

\cp linux-2.4.18-14custom/arch/i386/kernel/entry.S		/usr/src/linux-2.4.18-14custom/arch/i386/kernel/
\cp linux-2.4.18-14custom/include/asm-i386/unistd.h		/usr/src/linux-2.4.18-14custom/include/asm-i386/
\cp linux-2.4.18-14custom/include/linux/sched.h			/usr/src/linux-2.4.18-14custom/include/linux/
\cp linux-2.4.18-14custom/kernel/fork.c					/usr/src/linux-2.4.18-14custom/kernel/
\cp linux-2.4.18-14custom/kernel/sched.c				/usr/src/linux-2.4.18-14custom/kernel/


\cp hw2_syscalls.h		/usr/src/linux-2.4.18-14custom/
\cp main.c				/root/

\cp ../compileKernel	/root/



# Complex El-Ad Test
\cp linux-2.4.18-14custom/arch/i386/kernel/traps.c		/usr/src/linux-2.4.18-14custom/arch/i386/kernel/
\cp linux-2.4.18-14custom/kernel/ctx_log.h					/usr/src/linux-2.4.18-14custom/kernel/
\cp linux-2.4.18-14custom/kernel/exit.c					/usr/src/linux-2.4.18-14custom/kernel/
\cp linux-2.4.18-14custom/kernel/kassert.h					/usr/src/linux-2.4.18-14custom/kernel/

\cp -a -u tests/test_logger_src/user_mode/.			/root/
\cp hw2_syscalls.h							/root/
\cp runTest									/root/

# Simple El-Ad Test
\cp -a -u tests/test_simple/.							/root/
\cp tests/simpleTest								/root/


# Anna's friend's Test7
#\cp tests/tests7/test10.c		/root/test.c


#echo Done copying!
